config/routes.rb
Rails.application.routes.draw do

  root 'page#index'
  get 'services'   => 'page#services'
  get 'contact_us' => 'page#contact_us'
  get 'about'   => 'page#about'
  get 'portfolio'  => 'page#portfolio'
  resources :quote_requests, only: [:index, :new, :create, :destroy] do
    collection do
      get 'success'
    end
  end

end

app/models/quote_request.rb
class QuoteRequest < ActiveRecord::Base
  serialize :needs, Array

  validate :contact_presence

  def contact_presence
    if phone.blank? and email.blank?
      errors.add(:base, 'need_contact_info')
      return false
    else
      return true
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale

  layout "application"

  # def default_url_options(options={})
  #   { :locale => I18n.locale == I18n.default_locale ? nil : I18n.locale  }
  # end

  private
  def set_locale
    I18n.locale = extract_locale_from_domain || I18n.default_locale
    # I18n.locale = :en
  end

  def extract_locale_from_domain
    parsed_locale = request.host.split('.').last
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController

  def index
  end

  def about
  end

  def contact_us
  end

  def services
  end

  def portfolio
  end
end

app/controllers/quote_requests_controller.rb
class QuoteRequestsController < ApplicationController
  before_action :set_quote_request, only: [:show, :destroy]
  before_filter :authenticate, only: [:index, :destroy]

  # GET /quote_requests
  # GET /quote_requests.json
  def index
    @quote_requests = QuoteRequest.all
  end

  # DELETE /quote_requests/1
  # DELETE /quote_requests/1.json
  def destroy
    @quote_request.destroy
    respond_to do |format|
      format.html { redirect_to quote_requests_url, notice: 'Quote request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /quote_requests/new
  def new
    @quote_request = QuoteRequest.new
  end

  def success
  end

  # POST /quote_requests
  # POST /quote_requests.json
  def create
    @quote_request = QuoteRequest.new(quote_request_params)


    if @quote_request.save
      uploaded_io = params[:quote_request][:file]

      if (uploaded_io)
        @quote_request.attachment = uploaded_io.original_filename
        File.open(Rails.root.join('public', 'uploads', @quote_request.id.to_s+uploaded_io.original_filename), 'wb') do |file|
          file.write(uploaded_io.read)
        end
      end

      Notification.send_new_quote_request(@quote_request).deliver_now
      redirect_to success_quote_requests_path
    else
      render 'new'
    end
  end

  protected
    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == "ze" && password == "brains"
      end
    end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote_request
      @quote_request = QuoteRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_request_params
      params.require(:quote_request).permit(:name, :email, :phone, :company_name, :url, :description, needs: [])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/quote_requests_helper.rb
module QuoteRequestsHelper
end

app/views/layouts/_footer.html.haml
.navigaton-container
#footer-navigation
  .row
    .large-12.text-center
      %h3.logo
        =link_to root_path do
          %i.icon.icon-zebrains
          Zebrains
    .large-12.columns.text-center
      %ul.inline-list
        = render 'layouts/navigation_links'
#copyrates
  .row
    .large-4.columns.text-center.large-text-left
      %small
        &copy;
        = Date.today.year
        Zebrains company
    .large-4.columns.text-center
      %ul.inline-list
        %li
          =link_to "https://www.facebook.com/ITECH.group", target:"_blank" do
            %i.icon.icon-facebook
        %li
          =link_to "http://twitter.com/#!/ITECH_group", target:"_blank" do
            %i.icon.icon-twitter
        %li
          =link_to "https://plus.google.com/u/0/110500128245427285169/posts?cfem=1", target:"_blank" do
            %i.icon.icon-google
        %li
          =link_to "skype:zebrains.com?chat", target:"_blank" do
            %i.icon.icon-skype
        %li
          = link_to "http://telegram.me/zebrains", target:"_blank" do
            %i.icon.icon-telegram
    .large-4.columns.text-center.large-text-right
      =link_to contact_us_path do
        %small
          =t 'navigation_links.feedback'

app/views/layouts/_head.html.haml
%title= content_for?(:title) ? yield(:title) : "ZeBrains"
%meta{:name => "title", :content => "#{content_for?(:title) ? yield(:title) : t("meta.title")}"}
%meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : t("meta.description")}"}


%meta{:name => "google-site-verification", :content => "tEA6KmjP-XvR3jFIEFvktwboTnrBAye2gfL6AvALA1s"}
%meta{:name => 'yandex-verification', :content => '6e2491722262e464'}

%meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}

= csrf_meta_tags

= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true

-# Modernizr is required for Zurb Foundation
= javascript_include_tag "vendor/modernizr"
= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp"
= javascript_include_tag "application", "data-turbolinks-track" => true

= favicon_link_tag "/icon/apple-icon-57x57.png", rel: "apple-touch-icon", sizes: "57x57"
= favicon_link_tag "/icon/apple-icon-60x60.png", rel: "apple-touch-icon", sizes: "60x60"
= favicon_link_tag "/icon/apple-icon-72x72.png", rel: "apple-touch-icon", sizes: "72x72"
= favicon_link_tag "/icon/apple-icon-76x76.png", rel: "apple-touch-icon", sizes: "76x76"
= favicon_link_tag "/icon/apple-icon-114x114.png", rel: "apple-touch-icon", sizes: "114x114"
= favicon_link_tag "/icon/apple-icon-120x120.png", rel: "apple-touch-icon", sizes: "120x120"
= favicon_link_tag "/icon/apple-icon-144x144.png", rel: "apple-touch-icon", sizes: "144x144"
= favicon_link_tag "/icon/apple-icon-152x152.png", rel: "apple-touch-icon", sizes: "152x152"
= favicon_link_tag "/icon/apple-icon-180x180.png", rel: "apple-touch-icon", sizes: "180x180"

= favicon_link_tag "/icon/android-icon-192x192.png", rel: "icon", sizes: "192x192", type: "image/png"
= favicon_link_tag "/icon/favicon-32x32.png", rel: "icon", sizes: "32x32", type: "image/png"
= favicon_link_tag "/icon/favicon-96x96.png", rel: "icon", sizes: "96x96", type: "image/png"
= favicon_link_tag "/icon/favicon-16x16.png", rel: "icon", sizes: "16x16", type: "image/png"

%link{:rel => "manifest", :href => "/icon/manifest.json"}
%meta{:name => "msapplication-TileColor", :content => "#ffffff"}
%meta{:name => "msapplication-TileImage", :content => "/icon/ms-icon-144x144.png"}
%meta{:name => "theme-color", :content => "#ffffff"}

app/views/layouts/_index_magellan_navigation.html.haml
#navigation.contain-to-grid{"data-magellan-expedition" => ""}
  %nav.top-bar{"data-topbar" => true, "role" => "navigation"}
    %ul.title-area
      %li.name
        = link_to root_path do
          %i.icon.icon-zebrains>
          %span.red>ZE
          %span>BRAINS
      %li.toggle-topbar.menu-icon
        %a{:href => "#"}
          %span
            Menu
    %section.top-bar-section
      %ul.left.top-bar__navigation-links
        %li{"data-magellan-arrival" => "zebra-road-bg"}
          %a{"href" => "#"}
            =t "navigation_links.home"
        %li{"data-magellan-arrival" => "what-we-do"}
          %a{"href" => "#what-we-do"}
            =t "navigation_links.what_we_do"
        %li{"data-magellan-arrival" => "technology"}
          %a{"href" => "#technology"}
            =t "navigation_links.about"
        -#%li{"data-magellan-arrival" => "why-you-need"}
        -#  %a{"href" => "#why-you-need"}
        -#    =t "navigation_links.why_you_need"
        -#%li
        -#  %a{:href => "#", "data-reveal-id" => "troppus-login"}
        -#    =t "navigation_links.client_area"
        %li{"data-magellan-arrival" => "contacts"}
          %a{"href" => "#contacts"}
            =t "navigation_links.contacts"
        = active_link_to new_quote_request_path, wrap_tag: "li", class: "red" do
          =t "navigation_links.get_quote"
      %ul.right.top-bar__right-menu
        %li#phone-link
          = link_to "tel:+79278203777" do
            %i.icon.icon-phone<
            +7 (927) 820-37-77
        %li{class: ("active" if I18n.locale == :en)}
          = link_to "En", url_for('http://zebrains.com')
        %li.divider
        %li{class: ("active" if I18n.locale == :ru)}
          = link_to "Ru", url_for('http://zebrains.ru')

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
#navigation.contain-to-grid{:class => local_assigns[:sticky] ? "sticky" : "fixed" }
  %nav.top-bar{"data-topbar" => true, "role" => "navigation"}
    %ul.title-area
      %li.name
        = link_to root_path do
          %i.icon.icon-zebrains>
          %span.red>ZE
          %span>BRAINS
      %li.toggle-topbar.menu-icon
        %a{:href => "#"}
          %span
            Menu
    %section.top-bar-section
      %ul.left.top-bar__navigation-links
        = render 'layouts/navigation_links'
      %ul.right.top-bar__right-menu
        %li#phone-link
          = link_to "tel:+79278203777" do
            %i.icon.icon-phone<
            +7 (927) 820-37-77
        %li{class: ("active" if I18n.locale == :en)}
          = link_to "En", url_for('http://zebrains.com')
        %li.divider
        %li{class: ("active" if I18n.locale == :ru)}
          = link_to "Ru", url_for('http://zebrains.ru')

app/views/layouts/_navigation_links.html.haml
= active_link_to root_path(:anchor => ""), :active => [["page"], ["index"]], wrap_tag: "li" do
  =t "navigation_links.home"
= active_link_to root_path(:anchor => "what-we-do"), :active => [["page"], ["index"]],  wrap_tag: "li" do
  =t "navigation_links.what_we_do"
= active_link_to root_path(:anchor => "technology"), :active => [["page"], ["index"]], wrap_tag: "li" do
  =t "navigation_links.about"
-#= active_link_to root_path(:anchor => "why-you-need"), :active => [["page"], ["index"]], wrap_tag: "li" do
-#  =t "navigation_links.why_you_need"
= active_link_to root_path(:anchor => "contacts"), :active => [["page"], ["index"]], wrap_tag: "li" do
  =t "navigation_links.contacts"
-#%li
-#  %a{:href => "#", "data-reveal-id" => "troppus-login"}
-#    =t "navigation_links.client_area"
= active_link_to new_quote_request_path, wrap_tag: "li", class: "red" do
  =t "navigation_links.get_quote"

app/views/layouts/application.html.haml
!!!
%html{"lang" => I18n.locale}
  %head
    = render "layouts/head"
  %body
    %header
      = content_for?(:navigation) ? yield(:navigation) : render("layouts/navigation")
    %main#main{:role => "main"}
      = render "layouts/messages"
      = yield
      %footer#body-footer.full-width
        = content_for?(:footer) ? yield(:footer) : render("layouts/footer")
    -##troppus-login.reveal-modal.text-center{"data-reveal" => true, "aria-labelledby" => "troppus-login-title", "aria-hidden" => true, "role" => "dialog"}
    -#  %h2#troppus-login-title
    -#    =t :troppus_login_title
    -#
    -#  =simple_form_for :troppus_login, url: "http://troppus.ru"  do |f|
    -#    .row
    -#      .large-10.large-centered.columns.text-left
    -#        =f.input :email, required: false, placeholder: t(:email_mask)
    -#        =f.input :password, as: :password, required: false, placeholder: t(:password_mask)
    -#    .row
    -#      .large-10.large-centered.columns.text-center
    -#        =f.submit t(:login_button), class: 'button'
    -#        %br
    -#        =link_to t(:forgot_passoword_button), "http://troppus.ru"
    -#  %a.close-reveal-modal{"aria-label" => "Close"}
    -#    &#215;

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-61726838-2', 'auto');
      ga('send', 'pageview');

app/views/notification/send_new_quote_request.html.haml
=@quote_request.attributes

app/views/page/_about_company.html.haml
%section.full-width.about_company#about-company{"data-magellan-destination" => "about-company"}
  .row.text-center.full-width
    .large-12.columns
      .row
        .large-12.columns.text-center
          %h2
            =t('about_company.title')
          %p
            =t('about_company.text').html_safe
      .row
        .slider
          -[ "anadolu", "auchan", "bolshoi", "good-food", "just-for-you", "mitsubishi", "philips", "sony", "wwf" ].each do |img|
            .our_friends_logo
              %img{"src"=>"assets/friends/central-images/#{img}-min.jpg", "alt" => ""}

      .row.last-line

app/views/page/_chat_example.html.haml
.chat-example
  .wrapper
    .sidebar
      %ul.chat-contacts
        %li.contacts-item.js-contacts-item.active(data-dialog="0")
          .image-holder
            =image_tag("/assets/avatars/1-min.png", {"alt" => ""})
          .contact
            %p.contact-name
              =t("chats.bot1.contact-name")
            %p.contact-status
              Online
        %li.contacts-item.js-contacts-item(data-dialog="1")
          .image-holder
            =image_tag("/assets/avatars/2-min.png", {"alt" => ""})
          .contact
            %p.contact-name
              =t("chats.bot2.contact-name")
            %p.contact-status
              Online
        %li.contacts-item.js-contacts-item(data-dialog="2")
          .image-holder
            =image_tag("/assets/avatars/3-min.png", {"alt" => ""})
          .contact
            %p.contact-name
              =t("chats.bot3.contact-name")
            %p.contact-status
              Online
    .content
      .container.js-container

app/views/page/_contacts.html.haml
%section.full-width.contacts#contacts{"data-magellan-destination" => "contacts"}
  #map-ulianovsk.map-canvas.active
  #map-london.map-canvas
  #map-moscow.map-canvas
  #contacts-container.white
    .row
      .large-12
        %h2.white.text-center
          =t ("contacts.title")
    .row.text-center.full-width
      .large-3.small-3.columns.contact-blocks
        .contact-block
          %b
            =t ("contacts.lo.city")
          %br
          =t ("contacts.lo.phone")
          %br
          =t ("contacts.lo.email")

        .contact-block
          %b
            =t ("contacts.mo.city")
          %br
          =t ("contacts.mo.address")
          %br
          =t ("contacts.mo.phone")
          %br
          =t ("contacts.mo.email")
          %br
          %a.show-on-map.hide-for-small-only(data-name="moscow"
          data-map="map-moscow"
          data-latlng='{"latitude":"55.708551","longitude":"37.653338"}'
          data-center='{"latitude":"55.711551","longitude":"37.638338"}'
          )
            =t ("contacts.show_on_map")
        .contact-block
          %b
            =t ("contacts.ul.city")
          %br
          =t ("contacts.ul.address")
          %br
          =t ("contacts.ul.phone")
          %br
          =t ("contacts.ul.email")
          %br
          %a.show-on-map.active.hide-for-small-only(data-name="ulianovsk"
          data-map="map-ulianovsk"
          data-latlng='{"latitude":"54.344703","longitude":"48.371977"}'
          data-center='{"latitude":"54.344503","longitude":"48.371977"}'
          )
            =t ("contacts.show_on_map")
        .large-9.small-9.columns

app/views/page/_how_we_work.html.haml
%section.full-width.how-we-work#how-we-work
  .row.text-center
    .large-12.columns
      %h2
        =t('steps_block.title')
      %p
        =t('steps_block.text').html_safe
  .row.text-center.ticket-steps
    .ticket-step.large-4.small-6.columns
      %i.icon.icon-statement.red
      %i.icon.icon-angle-right.show-for-large-only
      %h3
        %span.base
          01.
        %span.black
          =t('steps_block.1_title')
      %small
        =t('steps_block.1_text')
    .ticket-step.large-4.small-6.columns
      %i.icon.icon-performance.red
      %i.icon.icon-angle-right.show-for-large-only
      %h3
        %span.base
          02.
        %span.black
          =t('steps_block.2_title')
      %small
        =t('steps_block.2_text')
    .ticket-step.large-4.small-6.columns
      %i.icon.icon-work.red
      %h3
        %span.base
          03.
        %span.black
          =t('steps_block.4_title')
      %small
        =t('steps_block.3_text')
    .ticket-step.large-4.large-offset-2.small-6.columns
      %i.icon.icon-verification.red
      %i.icon.icon-angle-right.show-for-large-only
      %h3
        %span.base
          04.
        %span.black
          =t('steps_block.5_title')
      %small
        =t('steps_block.5_text')
    .ticket-step.large-4.small-6.end.columns
      %i.icon.icon-case.red
      %h3
        %span.base
          05.
        %span.black
          =t('steps_block.6_title')
      %small
        =t('steps_block.6_text')

  %br
  %br
  .row.text-center
    .large-12
      = link_to t(:get_activity_button), new_quote_request_path, class: "button"

app/views/page/_main.html.haml
%section.zebra-road-bg.full-screen#zebra-road-bg{"data-magellan-destination" => "zebra-road-bg"}
  %h3.logo.text-center
    =link_to root_path do
      %i.icon.icon-zebrains
      Zebrains
  .row
    .large-12.text-center.white.slogan-container
      %h1
        =t(:slogan_tite).html_safe
      %p
        =t(:welcome_text).html_safe

  .row
    .span

  .get-btn-container
    .text-center
      =link_to t(:get_quote_button1), new_quote_request_path, class: "button"

  #scroll-down.text-center
    =link_to "#what-we-do" do
      %i.icon.icon-mouse.bounce
      -#%br
      -#=t :scroll_down

.full-width
  = render "layouts/index_magellan_navigation"

app/views/page/_our_plans_section.html.haml
%section.our-plans{"data-magellan-destination" => "our-plans"}
  %a{"name" => "our-plans"}
  .row.text-center
    .large-12.columns
      %h2
        =t('our_plans.title')
      %p=t('our_plans.text').html_safe
  .row{"data-equalizer" => ''}

    .large-4.columns
      %ul.pricing-table.smoke-bg{"data-equalizer-watch" => ''}
        %li.title
          =t("our_plans.business.title")
        %li.description
          =t("our_plans.business.descr")
        %li.price
          .price__block.text-right
            .price__text.price__text--big.red
              = t('price.currency').html_safe if I18n.locale != :ru
            .price__text.price__text--small
              =t 'price.from'
          .price__cost.red
            = t 'our_plans.business.price'
          .price__block.text-left
            .price__text.price__text--big.red
              =t(I18n.locale != :ru ? 'price.cost_zero' : 'price.currency').html_safe
            .price__text.price__text--small
              =t 'price.monthly'
        %li.bullet-item
          =t("our_plans.business.hours")
        %li.bullet-item
          =t("our_plans.business.hourly_cost").html_safe
        %li.bullet-item
          =t("our_plans.business.advantage_1")
        %li.bullet-item
          =t("our_plans.business.advantage_2")
        %li.cta-button
          =link_to t(:buy_it_button), new_quote_request_path, class: "button secondary"

    .large-4.columns
      %ul.pricing-table{"data-equalizer-watch" => ''}
        %li.title
          %div.recomended.text-center
            %span.alert.label
              =t :recomended
          =t("our_plans.standart.title")
        %li.description
          =t("our_plans.standart.descr")
        %li.price
          .price__block.text-right
            .price__text.price__text--big.red
              = t('price.currency').html_safe if I18n.locale != :ru
            .price__text.price__text--small
              =t 'price.from'
          .price__cost.red
            = t 'our_plans.standart.price'
          .price__block.text-left
            .price__text.price__text--big.red
              =t(I18n.locale != :ru ? 'price.cost_zero' : 'price.currency').html_safe
            .price__text.price__text--small
              =t 'price.monthly'
        %li.bullet-item
          =t("our_plans.standart.hours")
        %li.bullet-item
          =t("our_plans.standart.hourly_cost").html_safe
        %li.bullet-item
          =t("our_plans.standart.advantage_1")
        %li.bullet-item
          =t("our_plans.standart.advantage_2")
        %li.cta-button
          =link_to t(:buy_it_button), new_quote_request_path, class: "button"

    .large-4.columns
      %ul.pricing-table.smoke-bg{"data-equalizer-watch" => ''}
        %li.title
          =t("our_plans.start.title")
        %li.description
          =t("our_plans.start.descr")
        %li.price
          .price__cost.price__cost--free
            %span.red
              =t 'price.free'
            %span.base
              *
        %li.bullet-item
          =t("our_plans.start.hours")
        %li.bullet-item
          =t("our_plans.start.hourly_cost").html_safe
        %li.bullet-item
          =t("our_plans.start.advantage_1")
        %li.bullet-item
          =t("our_plans.start.advantage_2")
        %li.cta-button
          =link_to t(:buy_it_button), new_quote_request_path, class: "button secondary"
  .row.text-center
    .large-12.columns
      =t("our_plans.note_1").html_safe

app/views/page/_technology.html.haml
%section.full-width.technology#technology{"data-magellan-destination" => "technology"}
  .row.full-width
    .large-8.small-12.columns.sla-block
      %h2.white.text-center
        =t('technology_block.title')
      =render "chat_example"

    .large-4.small-12.columns
      .row.we_can_section
        .large-12.columns
          .text-center
            %h2
              =t('we_can_block.title')
        .large-8.large-centered.columns
          .row.text-center
            - {'telegram': 'Telegram', 'skype': 'Skype', 'slack': 'Slack', 'whatsapp':'WhatsApp', 'wechat':'Wechat', 'snapchat':'Snapchat', 'viber':'Viber', 'line': 'Line', 'facebook_messenger': 'Facebook Messenger'}.each do |key, name|
              .large-4.small-4.columns.left.we_can_logo
                =image_tag "/assets/we_can_logos/#{key}-min.png", alt: "", class: "messenger-icon"
                %span
                  =name

app/views/page/_we_are.html.haml
%section.full-width.we-are#we-are
  .row.text-center
    .large-12.columns
      %h2
        =t("we_are.text")

app/views/page/_why_you_need.html.haml
%section.full-width.our-capacity#why-you-need
  .row.text-center
    .large-12.columns
      %h2.white
        =t :why_you_need_title
      %p
        =t('why_you_need_text').html_safe

app/views/page/contact_us.html.haml
%section.contact_us.full-height.zebra-bg
  %h1.text-center
    =t :contact_us_title
  =simple_form_for QuoteRequest.new do |f|
    .row
      .large-6.large-centered.small-12.columns
        =f.text_field :name, label: false,
            placeholder: QuoteRequest.human_attribute_name('name'),
            title: QuoteRequest.human_attribute_name('tooltip_name'),
            "data-tooltip" => "",
            "aria-haspopup" => true
    .row
      .large-6.large-centered.small-12.columns
        =f.text_field :email, label: false,
            placeholder: QuoteRequest.human_attribute_name('email'),
            title: QuoteRequest.human_attribute_name('tooltip_email'),
            "data-tooltip" => "",
            "aria-haspopup" => true
    .row
      .large-6.large-centered.small-12.columns
        =f.text_field :phone, label: false,
          placeholder: QuoteRequest.human_attribute_name('phone'),
          title: QuoteRequest.human_attribute_name('tooltip_phone'),
          "data-tooltip" => "",
          "aria-haspopup" => true
    .row
      .large-6.large-centered.small-12.columns.form-section-title
        =QuoteRequest.human_attribute_name('description')
    .row
      .large-6.large-centered.small-12.columns
        =f.text_area :description
    .row
      .large-12.columns.text-center
        =f.submit t(:send_quote_request_button), class: 'button'

app/views/page/index.html.haml
- content_for(:navigation) do
  %div

=render "main"
=render "what_we_do"
=render "why_you_need"
=render "technology"
=render "how_we_work"
=render "contacts"
=render "about_company"
-#=render "we_are"

app/views/page/services.html.haml
%section.full-width
  .row.text-center
    .large-12.columns
      %h1
        =t :services_title
      %p=t('services_text').html_safe
%section.full-width.services.zebra-bg
  .row
    .medium-6.columns
      %h2
        =t :service_design_title
      %p
        =t('service_design_text').html_safe
    .medium-6.columns
      = image_tag("service-design.jpg", class: "service-image show-for-medium-up")
%section.full-width.services
  .row
    .medium-6.columns
      = image_tag("service-coding.jpg", class: "service-image show-for-medium-up")
    .medium-6.columns
      %h2
        =t :service_coding_title
      %p
        =t('service_coding_text').html_safe
%section.full-width.services.zebra-bg
  .row
    .medium-6.columns
      %h2
        =t :service_promo_title
      %p
        =t('service_promo_text').html_safe
    .medium-6.column
      = image_tag("service-promo.jpg", class: "service-image show-for-medium-up")

app/views/quote_requests/index.html.haml
%h1 Listing quote_requests

- @quote_requests.each do |quote_request|
  .row
    .large-12.columns
      =quote_request.attributes
      %br
      = link_to 'Destroy', quote_request, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "button"

app/views/quote_requests/new.html.haml
%section.contact_us
  .row
    .large-12.columns.text-center
      %h1
        =t :lets_work_together
  = render 'form'

app/views/quote_requests/success.html.haml
%section.full-width.success.zebra-bg.full-height
  .row
    .large-12.columns.text-center
      %h1
        =t :quote_request_success_title
      %p
        =t :quote_request_success_text
        %br
        %br
        =link_to t(:go_home_link), root_path, class: "button"